# **Задача 1**

# A+2B

In [ ]:
import numpy as np

In [ ]:
A = np.matrix([[1, 2, 1],
               [-2, 1, 1]])

In [ ]:
B = np.matrix([[3, 1],
               [-1, 0],
               [2, 4]])

In [ ]:
A+2*np.transpose(B)

matrix([[7, 0, 5],
        [0, 1, 9]])

# B+2C

In [ ]:
C = np.matrix([[-2, 2],
              [1, -1],
              [1, 2]])

In [ ]:
B+2*C

matrix([[-1,  5],
        [ 1, -2],
        [ 4,  8]])

# **Задача 2**

In [ ]:
w = np.zeros((8,8),dtype=int)
w[1::2,::2] = 1
w[::2,1::2] = 1
print(w)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Альтернатива

In [ ]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# **Задача 3**

In [ ]:
v = np.arange(0, 1.5, 0.1).reshape((5, 3))
y = np.arange(1, 7, 1).reshape((3, 2))
print (np.dot(v, y))

[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


# **Задача 4**

In [ ]:
p=np.arange(start=1, stop=72, step=2, dtype=np.int32)
print ('Исходный вектор:\n', p)
k=np.fromiter((p for p in p if p%3 == 0), dtype = p.dtype)
print ('Вектор со значениями, кратные 3:\n', k)

Исходный вектор:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]
Вектор со значениями, кратные 3:
 [ 3  9 15 21 27 33 39 45 51 57 63 69]
